// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOhN6BRk8stcZhcOifO7JpkT5zAkMef1c',
    appId: '1:1024058297359:web:341602a596813e11eee77a',
    messagingSenderId: '1024058297359',
    projectId: 'jnfinzanzaapp',
    authDomain: 'jnfinzanzaapp.firebaseapp.com',
    storageBucket: 'jnfinzanzaapp.firebasestorage.app',
    measurementId: 'G-DQD4E56VMS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiPe0yGNtetSDWfOG1j6lhVrty236ND4A',
    appId: '1:1024058297359:android:da658ec06560ae9eeee77a',
    messagingSenderId: '1024058297359',
    projectId: 'jnfinzanzaapp',
    storageBucket: 'jnfinzanzaapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrAWwJzi-qKKA79OSxX4FTJyRdDDkOua0',
    appId: '1:1024058297359:ios:cafcd9546c0107d7eee77a',
    messagingSenderId: '1024058297359',
    projectId: 'jnfinzanzaapp',
    storageBucket: 'jnfinzanzaapp.firebasestorage.app',
    iosBundleId: 'com.example.jnFinzanzaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOhN6BRk8stcZhcOifO7JpkT5zAkMef1c',
    appId: '1:1024058297359:web:4972e319b8795e21eee77a',
    messagingSenderId: '1024058297359',
    projectId: 'jnfinzanzaapp',
    authDomain: 'jnfinzanzaapp.firebaseapp.com',
    storageBucket: 'jnfinzanzaapp.firebasestorage.app',
    measurementId: 'G-QVLY7NFNLY',
  );
}
